import type { SaleDto } from '@gulbahor/core'

const som = (amount: number) => amount * 100

/** A receipt with a little of everything on it, so that every switch has something to show or hide. */
export function sampleSale(shop: { name: string; address: string | null; phone: string | null }): SaleDto {
  return {
    id: 'sample',
    number: 'CH-000128',
    status: 'completed',
    soldAt: '2026-10-05T14:32:00+05:00',
    locationName: shop.name,
    locationAddress: shop.address,
    locationPhone: shop.phone,
    registerName: 'Kassa 1',
    cashierName: 'Dilnoza Karimova',
    sellerName: 'Sardor Aliyev',
    customerId: 'sample',
    customerName: 'Nodira Yusupova',
    priceTypeName: null,
    promoCode: null,
    subtotal: som(1_170_000),
    discount: som(187_000),
    autoDiscount: som(117_000),
    autoReason: 'Sodiqlik 10%',
    total: som(983_000),
    costUzs: null,
    returnedTotal: 0,
    shiftId: 'sample',
    shiftNumber: 'SM-000041',
    uzsPerUsd: null,
    changeUzs: som(17_000),
    changeUsd: 0,
    rounding: 0,
    note: null,
    voidedAt: null,
    voidedByName: null,
    voidReason: null,
    approvedByName: null,
    lines: [
      {
        id: 'l1',
        variantId: 'v1',
        productName: "Ko'ylak",
        label: 'Qora, M',
        sku: '1042-03',
        qty: 1,
        price: som(900_000),
        discount: som(160_000),
        autoDiscount: som(90_000),
        promotionName: null,
        promoDiscount: 0,
        total: som(740_000),
        epc: null,
        returnedQty: 0,
        returnedTotal: 0,
      },
      {
        id: 'l2',
        variantId: 'v2',
        productName: 'Sharf',
        label: 'Bej',
        sku: '2210-01',
        qty: 3,
        price: som(90_000),
        discount: som(27_000),
        autoDiscount: som(27_000),
        promotionName: null,
        promoDiscount: 0,
        total: som(243_000),
        epc: null,
        returnedQty: 0,
        returnedTotal: 0,
      },
    ],
    payments: [
      {
        method: 'cash',
        accountName: 'Kassa 1',
        currency: 'UZS',
        amount: som(500_000),
        base: som(500_000),
        fx: 0,
        reference: null,
      },
      {
        method: 'card',
        accountName: 'Humo *3073',
        currency: 'UZS',
        amount: som(500_000),
        base: som(500_000),
        fx: 0,
        reference: null,
      },
    ],
    returns: [],
  } as unknown as SaleDto
}
